services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: php:8.2-fpm
    container_name: symfony_php
    volumes:
      - .:/var/www/html
      - ./config/jwt:/var/www/html/config/jwt
    depends_on:
      - database
      - rabbitmq

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: postgres:16-alpine
    container_name: symfony_db
    environment:
      POSTGRES_DB: habitra_database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "admin"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  node_worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.node
    depends_on:
      - rabbitmq
    networks:
      - default

volumes:
  database_data:
